### ISSUE TITLE
Authentication issue on Deleted Cookies

### ISSUE THREAD

**Issue by MarJose123** [work-mate/nuxt-auth-module#4]
I tried to delete the Session Cookies and navigating to protected page and still able to load the page.

I think the the `loggedIn` from ` useAuth()` composable needs to check and validate the the session cookies from the storage on every request.

**Comment by dev-davexoyinbo** [comment]
Noted. I would get to this

**Comment by dev-davexoyinbo** [comment]
@MarJose123 , this has now been fixed in the v1.2.0
