### ISSUE TITLE
Features: Add callback redirect page

### ISSUE THREAD

**Issue by MarJose123** [work-mate/nuxt-auth-module#5]
Add a callback redirect page after the user login.

**Scenario**:
If the user navigates to the protected page without logging in, then the user should be redirected to the to the login page and once the user successfully logged in, it should redirect to the protected page he visited before.

**Comment by dev-davexoyinbo** [comment]
Noted. I would work on this. Thank you for the feedback

**Comment by dev-davexoyinbo** [comment]
@MarJose123 , this has now been added to the v1.2.0

**Comment by dev-davexoyinbo** [comment]
@MarJose123 , this has now been added to the v1.2.0
